In [23]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [24]:
url = "https://www.ccny.cuny.edu/registrar/fall"
response = requests.get(url)
soup = BeautifulSoup(response.content, "html.parser")
print(soup.title)

<title>Fall 2021 Academic Calendar | The City College of New York</title>

In [25]:
table = soup.find("table")
rows = table.find_all("tr")

In [26]:
events = []

for row in rows[1:]:
    
    cols = row.find_all("td")
    
    if len(cols) >= 3:
        
        date = cols[0].text.strip()
        dow = cols[1].text.strip()
        text = cols[2].text.strip()
        
        events.append([date, dow, text])

print(events[:5])

[['August 01', 'Sunday', 'Application for degree for January and February 2022 begins'], ['August 18', 'Wednesday', 'Last day to apply for Study Abroad'], ['August 24', 'Tuesday', 'Last day of Registration;\n\t\t\tLast day to file ePermit for the Fall 2021;\n\t\t\tLast day to drop classes for 100% tuition refund;'], ['August 25', 'Wednesday', 'Start of Fall Term;\n\t\t\tClasses begin;\n\t\t\tInitial Registration Appeals begin;'], ['August 25 - 31', 'Wednesday - Tuesday', 'Change of program period; late fees apply']]

In [27]:
df = pd.DataFrame(events, columns=["date", "dow", "text"])
df.head()

,date,dow,text
0,August 01,Sunday,Application for degree for January and Februar...
1,August 18,Wednesday,Last day to apply for Study Abroad
2,August 24,Tuesday,Last day of Registration;\n\t\t\tLast day to f...
3,August 25,Wednesday,Start of Fall Term;\n\t\t\tClasses begin;\n\t\...
4,August 25 - 31,Wednesday - Tuesday,Change of program period; late fees apply

In [28]:
df["date"] = [d.split("-")[0].strip() for d in df["date"]]
df["date"] = df["date"] + " 2021"
# convert to datetime
df["date"] = pd.to_datetime(df["date"], errors="coerce")
df.head()

,date,dow,text
0,2021-08-01,Sunday,Application for degree for January and Februar...
1,2021-08-18,Wednesday,Last day to apply for Study Abroad
2,2021-08-24,Tuesday,Last day of Registration;\n\t\t\tLast day to f...
3,2021-08-25,Wednesday,Start of Fall Term;\n\t\t\tClasses begin;\n\t\...
4,2021-08-25,Wednesday - Tuesday,Change of program period; late fees apply

In [29]:
df = df.set_index("date")
df.head()

,dow,text
date,,
2021-08-01,Sunday,Application for degree for January and Februar...
2021-08-18,Wednesday,Last day to apply for Study Abroad
2021-08-24,Tuesday,Last day of Registration;\n\t\t\tLast day to f...
2021-08-25,Wednesday,Start of Fall Term;\n\t\t\tClasses begin;\n\t\...
2021-08-25,Wednesday - Tuesday,Change of program period; late fees apply